export const zambianCards: string[][] = [
  // ============= POP CULTURE & TRENDING =============
  ["TikTok Dance", "Video", "Viral", "Social Media", "Challenge"],
  ["Zed Twitter", "Zambian Twitter", "Trending", "Hashtag", "Social Media"],
  ["Ku Chalo", "World", "Zambia", "YouTube", "Internet"],
  ["Diamond TV", "TV", "Local Channel", "News", "Television"],
  ["Komboni Radio", "Radio", "Pobo", "Akuna Kulala", "94.9FM"],
  ["Load Shedding", "ZESCO", "Power Cut", "Electricity", "Darkness"],
  ["WhatsApp Group", "Chat", "Family", "Messages", "Green App"],
  ["Mobile Money Agent", "Booth", "Cash Out", "Transfer", "Float"],
  ["Zed Gossip", "Facebook Page", "Drama", "Celebrities", "Scandal"],
  ["ZNBC Memes", "TV1", "Funny", "Internet Jokes", "Broadcasting"],
  ["Slay Queen", "Instagram", "Fashion", "Lifestyle", "Social Media"],
  ["Ben Lombe", "Salon", "Comedian", "Zed Content", "YouTube"],
  ["Simon Mwewa Lane", "Vlogger", "Facebook", "Simoson", "Reflector Vest"],

  // ============= POLITICS & CURRENT AFFAIRS =============
  ["Hakainde Hichilema", "HH", "Bally", "UPND", "President"],
  ["Edgar Lungu", "ECL", "PF", "Former President", "Chagwa"],
  ["Michael Sata", "King Cobra", "PF", "Donchi Kubeba", "Former President"],
  ["Kenneth Kaunda", "KK", "First President", "Independence", "UNIP"],
  ["Levy Mwanawasa", "MMD", "Third", "Former President", "Anti-corruption"],
  ["Frederick Chiluba", "FTJ", "Democracy", "MMD", "Second President"],
  ["Rupiah Banda", "RB", "Bwezani", "Politician", "Former President"],
  ["Constitutional Court", "ConCourt", "Judges", "Legal", "Ruling"],
  ["CDF", "Loan", "Development", "Government", "Council"],
  ["Free Education", "Learning", "Government", "School", "UPND"],
  ["IMF Deal", "Loan", "Debt", "Re-structuring", "Economy"],
  ["By-election", "Voting", "Constituency", "Campaign", "Politics"],
  ["ACC", "Anti-Corruption", "Fraud", "Investigation", "Government"],
  ["Parliament", "MPs", "National Assembly", "Laws", "Debate"],
  ["ECZ", "Electoral Commission", "Voting", "Elections", "Results"],
  ["Cadre", "Political Supporter", "Violence", "Bus Station", "Politics"],

  // ============= FOOD & DRINK =============
  ["Nshima", "Mealie Meal", "Ubwali", "Staple", "White"],
  ["Vinkubala", "Caterpillars", "Mopane Worms", "Protein", "Fried"],
  ["Chikanda", "African Polony", "Orchid", "Vegetarian Meat", "Traditional"],
  ["Ifisashi", "Vegetables", "Groundnuts", "Pumpkin Leaves", "Soda"],
  ["Kapenta", "Small Fish", "Dried", "Eat", "Sardines"],
  ["Village Chicken", "Village", "Free Range", "Traditional", "Tough"],
  ["Munkoyo", "Drink", "Fermented", "Traditional", "Sweet"],
  ["Chibuku", "Shake Shake", "Beer", "Carton", "Traditional"],
  ["Bondwe", "Amaranthus", "Leafy Vegetable", "Traditional", "Green"],
  ["Inswa", "Flying", "Insect", "Rainy Season", "Eat"],
  ["Vitumbuwa", "Fritters", "Fry", "Street Food", "Dough"],
  ["Thobwa", "Fermented Drink", "Maize", "Sweet Sour", "Traditional"],
  ["Maheu", "Flavours", "Maize Drink", "Shake", "Sweet"],
  ["Bream", "Fish", "Kafue", "Grilled", "Fresh"],
  ["T-bone", "Steak", "Braai", "Meat", "Matebeto"],
  ["Mosi Lager", "Beer", "Zambian Breweries", "Golden", "Bottle"],
  ["Castle Lager", "Beer", "Bar", "South African", "Premium"],
  ["Eagle Lager", "Beer", "Affordable", "Bar", "Bottle"],

  // ============= CULTURE & TRADITIONS =============
  ["Lobola", "Bride Price", "Marriage Payment", "Traditional", "Dowry"],
  ["Kitchen Party", "Pre-wedding", "Women Only", "Advice", "Gifts"],
  ["Matebeto", "Food", "Marriage", "Bemba Tradition", "Feast"],
  ["Kuomboka", "Lozi Ceremony", "Barotse", "Flood", "Royal Barge"],
  ["Nc'wala", "Ngoni Ceremony", "First Fruits", "Eastern", "February"],
  ["Umutomboko", "Lunda Ceremony", "Chief Mwata Kazembe", "Luapula", "Dance"],
  ["Icilanga Mulilo", "Keeping Fire", "Mourning", "Funeral", "Tradition"],
  ["Chilanga Mulilo", "Marriage", "Ceremony", "Presentation", "Food"],
  ["Insaka", "Traditional Hut", "Meeting Place", "Shade", "Elders"],
  ["Ubuntu", "Humanity", "Philosophy", "Community", "African"],
  ["Chitenge", "African Print", "Wrapper", "Meters", "Women"],
  ["Bashikulu", "Grandfather", "Elder", "Respect", "Old Man"],
  ["Mukanda", "Boys Initiation", "Circumcision", "Ceremony", "Men"],

  // ============= COLLOQUIALISMS & SLANG =============
  ["Bally", "Father", "Old Man", "HH", "Dad"],
  ["Ka Something", "Small Amount", "Little Bit", "Some", "Few"],
  ["Exay", "Ohn", "Friend", "Guy", "Boyi"],
  ["Zigolo", "Sugar", "Water", "Drink", "Food"],
  ["Kaponya", "Bus Conductor", "Call Boy", "Change", "Transport"],
  ["Mayo", "Mother", "Mum", "Woman", "Respect"],
  ["Chibanda", "Ghost", "Spirit", "Scary", "Supernatural"],
  ["Bondi", "Home", "House", "Live", "Stay"],
  ["Kamtemba", "Kiosk", "Small Shop", "Corner Store", "Tuckshop"],
  ["Kapokola", "Police", "Officers", "Uniform", "Law"],
  ["Komboni", "Compound", "Township", "High Density", "Community"],
  ["Racks", "Money", "Cash", "Kwacha", "Currency"],
  ["Ndoshi", "Witch", "Witchcraft", "Magic", "Evil"],

  // ============= ZAMBIAN MUSIC =============
  ["Yo Maps", "Olios", "Kidist", "Aweah", "Komando"],
  ["Macky 2", "Kopala", "King Bugga", "Rap", "Ghetto President"],
  ["Chef 187", "Numero Uno", "Bon Appetit", "Lyrical Sensei", "Rap"],
  ["Slapdee", "King Dizzo", "Rap", "XYZ", "Chikali"],
  ["Mampi", "Queen Diva", "Walilowelela", "Singer", "Fashion"],
  ["Roberto", "Amarulah", "Singer", "R&B", "My Name is..."],
  ["Cleo Ice Queen", "Rapper", "Shoulda Coulda Woulda", "Hip Hop", "Dreamers"],
  ["T-Sean", "Baila", "Dancehall", "Producer", "CEO"],
  ["Jay Rox", "Zone Fam", "Scar", "Auto Pilot", "Calibre"],
  ["B-Flow", "Dear Mama", "Sunda Station", "Political Music", "Conscious"],
  ["Pompi", "Singer", "Gospel", "Mizu", "Rap"],
  ["Abel Chungu", "Gospel", "Worship", "Christian", "Singer"],
  ["Ephraim", "Son of Africa", "Gospel", "Worship", "Singer"],
  ["Mag44", "Rapper", "Christian", "Believe", "44Drums"],
  ["Amayenge", "Legendary Band", "Kalindula", "Alice Chuma", "Group"],
  ["PK Chishala", "Kalindula", "Na Musonda", "Glasses", "Umuntu Ni Bantu"],
  ["Angela Nyirenda", "Ngoni", "Female", "Vintage", "Singer"],
  ["Danny Kaya", "Kaya", "R&B", "Twaumfwa", "Singer"],
  ["Lily T", "Female Artist", "Singer", "Voice", "Mvela"],
  ["Wezi", "Heart of Africa", "Singer", "Actress", "Voice"],
  ["Chanda Na Kay", "Duo", "Zambian Music", "Kopala", "Young Artists"],
  ["4 Na 5", "Duo", "Party", "Kontolola", "Dance"],
  ["Drimz", "Mr Muziq", "Baila", "Producer", "Artist"],
  ["Jemax", "New Wave", "Hip Hop", "Rap", "Music"],

  // ============= INTERNATIONAL MUSIC =============
  ["Beyoncé", "Queen B", "Formation", "Single Ladies", "Jay-Z"],
  ["Drake", "Canadian", "Rapper", "OVO", "Hotline Bling"],
  ["Rihanna", "Barbados", "Umbrella", "Fenty", "Singer"],
  ["Burna Boy", "African Giant", "Nigerian", "Afrobeats", "Grammy"],
  ["Davido", "Aye", "Nigerian", "Fall", "Afrobeats"],
  ["Wizkid", "Starboy", "Nigerian", "Essence", "Afrobeats"],
  ["Amapiano", "South Africa", "Genre", "Dance", "Piano"],
  ["Diamond Platnumz", "Tanzanian", "Bongo Flava", "East Africa", "Simba"],
  ["Sauti Sol", "Kenya", "Melanin", "Afro", "Group"],
  ["Ed Sheeran", "British", "Shape of You", "Singer", "Guitar"],

  // ============= ZAMBIAN TV & FILM =============
  ["Zuba", "Zambezi Magic", "Lute", "Sosala", "TV Show"],
  ["Mpali", "Zambezi Magic", "Nguzu", "Farm", "Series"],
  ["Banja", "Comedy", "Family Show", "Zambian", "Muvi TV"],
  ["Love Games", "Drama Series", "Zambian", "Dating", "HIV/AIDS"],
  ["I Am Not A Witch", "Film", "Award Winning", "Rungano Nyoni", "International"],
  ["The Letter Reader", "Zambian Film", "Drama", "Local", "Movie"],
  ["Shaka Zulu", "Film", "Zulu King", "South Africa", "Cow-horn formation"],
  ["Suwi", "Drama Series", "Local", "TV Show", "Popular"],
  ["Kabanana", "Series", "Drama", "Jason", "TV"],
  ["Mwine Mushi", "Kasaka", "Comedy", "TV", "Village"],

  // ============= INTERNATIONAL FILM & TV =============
  ["Black Panther", "Wakanda", "Marvel", "Chadwick Boseman", "Superhero"],
  ["Money Heist", "La Casa de Papel", "Netflix", "Professor", "Spanish"],
  ["Squid Game", "Korean", "Netflix", "Deadly Games", "456"],
  ["Bridgerton", "Netflix", "Historical", "Romance", "Duke"],
  ["Game of Thrones", "Stark", "Dragon", "Winter", "Daenerys Targaryen"],
  ["The Queen", "Mzansi Magic", "South African", "Drama", "Telenovela"],
  ["Gomora", "Mzansi Magic", "South African", "Township", "Drama"],
  ["Blood and Water", "Netflix", "South African", "Teen Drama", "Cape Town"],
  ["Woman King", "Dahomey", "Warriors", "Viola Davis", "Fight"],
  ["Coming to America", "Eddie Murphy", "Comedy", "Prince", "Queens"],
  ["Titanic", "Ship", "Leonardo DiCaprio", "Romance", "Iceberg"],
  ["Avatar", "Blue People", "Pandora", "James Cameron", "3D"],
  ["Avengers", "Marvel", "Superheroes", "Thanos", "Infinity Stones"],
  ["Fast and Furious", "Cars", "Racing", "Vin Diesel", "Family"],
  ["Friends", "Sitcom", "Central Perk", "Ross and Rachel", "Comedy"],
  ["The Office", "Comedy", "Dunder Mifflin", "Michael Scott", "Workplace"],
  ["Stranger Things", "Netflix", "Upside Down", "Eleven", "80s"],
  ["Breaking Bad", "Walter White", "Meth", "Heisenberg", "Chemistry"],
  ["Narcos", "Pablo Escobar", "Colombia", "DEA", "Drugs"],
  ["Prison Break", "Michael Scofield", "Tattoo", "Escape", "Brothers"],

  // ============= SPORTS =============
  ["Chipolopolo", "Men", "National Team", "Football", "Zambia"],
  ["AFCON 2012", "Zambia", "Gabon", "Penalty", "Win"],
  ["Kalusha Bwalya", "Great Kalu", "Legend", "Footballer", "1988"],
  ["Fashion Sakala", "Rangers", "Striker", "Glasgow", "Chipolopolo"],
  ["Patson Daka", "Leicester City", "Striker", "Red Bull", "Football"],
  ["Enock Mwepu", "Football", "Brighton", "Midfielder", "Retired"],
  ["Barbra Banda", "Women's Football", "Striker", "Shanghai", "Copper Queens"],
  ["Samuel Matete", "400m Hurdles", "Olympics", "Athletics", "Legend"],
  ["Muzala Samukonga", "400m", "Commonwealth", "Gold", "Runner"],
  ["Boxing Day", "December 26", "Holiday", "Sports", "Celebration"],
  ["Heroes Stadium", "National", "Lusaka", "Football", "Venue"],
  ["Nkana FC", "Kalampa", "Red Devils", "Kitwe", "Wusakile"],
  ["Power Dynamos", "Aba Yellow", "Kitwe", "Arthur Davies", "Football"],
  ["Zesco United", "Team Ya Ziko", "Ndola", "Champions", "Football"],
  ["Green Buffaloes", "Army Team", "Lusaka", "Military", "Football"],
  ["Red Arrows", "Airmen", "Air Force", "Nkoloma", "Football"],
  ["Zanaco FC", "Bankers", "The Sensational", "Sunset", "Football"],

  // ============= BUSINESS & BRANDS =============
  ["Shoprite", "Supermarket", "Mall", "Groceries", "Red"],
  ["Pick n Pay", "Supermarket", "Groceries", "Smart Shopper", "Blue"],
  ["Trade Kings", "Boom", "Manufacturing", "Local Company", "Detergent"],
  ["Zambeef", "Meat", "Butchery", "ZamChick", "Zambia"],
  ["Zambian Breweries", "Mosi", "Beer", "Clear Beer", "SABMiller"],
  ["MTN", "Network", "Mobile", "Yellow", "Everywhere You Go"],
  ["Airtel", "Network", "Mobile", "Red", "The Smartphone Network"],
  ["Zamtel", "Network", "Government", "Green", "Telecommunications"],
  ["Stanbic Bank", "Blue", "Bank", "Moving Forward", "Financial"],
  ["Zanaco Bank", "Red", "Bank", "The People's Bank", "Commercial"],
  ["FNB", "First National", "Banking", "How Can We Help", "eWallet"],
  ["Game Stores", "Department Store", "Electronics", "Furniture", "Mall"],
  ["Hungry Lion", "Fast Food", "Chicken", "Franchise", "Orange"],
  ["Debonairs Pizza", "Pizza", "Delivery", "Fast Food", "Black"],
  ["Nando's", "Chicken", "Festa Fries", "Restaurant", "Flame Grilled"],
  ["ZESCO", "Electricity", "Power", "Utility", "Load Shedding"],

  // ============= GEOGRAPHY & PLACES =============
  ["Victoria Falls", "Mosi-oa-Tunya", "Tourism", "Waterfall", "Livingstone"],
  ["Kariba Dam", "Hydroelectric", "Lake", "Zimbabwe Border", "Power"],
  ["Zambezi River", "River", "Mwinilunga", "Water", "Indian Ocean"],
  ["Lake Tanganyika", "Top", "Tanzania", "Mpulungu", "Water"],
  ["Kafue National Park", "Largest", "Wildlife", "Busanga Plains", "Conservation"],
  ["South Luangwa", "Walking Safaris", "Leopards", "Mfuwe", "Valley"],
  ["Copperbelt", "Mining Region", "Ndola", "Kitwe", "Copper"],
  ["Lusaka Province", "Capital", "Central", "Town", "City"],
  ["Western Province", "Barotseland", "Mongu", "Floodplains", "Lozi"],
  ["Eastern Province", "Chipata", "Fort Jameson", "Malawi", "Chewa"],
  ["Northern Province", "Kasama", "Bemba", "Waterfalls", "Up"],
  ["Chirundu", "Border", "Zimbabwe", "Bridge", "One Stop"],
  ["Great East Road", "Chelston", "Highway", "Chipata", "Town"],
  ["Great North Road", "Miles", "Highway", "Emmasdale", "Longest"],
  ["Devil's Pool", "Victoria Falls", "Edge", "Swimming", "Dangerous"],
  ["Blue Lagoon", "Kafue Flats", "Park", "Birds", "Wetlands"],
  ["Mukuni Village", "Cultural", "Traditional", "Tourism", "Chief"],

  // ============= COMPOUNDS & TOWNSHIPS =============
  ["Kanyama", "Compound", "Largest", "John Laing", "Kwa"],
  ["Chibolya", "Compound", "Misisi", "George", "Illegal"],
  ["Matero", "Compound", "Metro", "Lusaka West", "Market"],
  ["Mandevu", "Compound", "Constituency", "Lusaka", "Beard"],
  ["Bauleni", "Compound", "Leopards Hill", "Market", "Ibex"],
  ["Kalingalinga", "Compound", "Mtendere", "Market", "Traffic Lights"],
  ["Garden Compound", "Garden", "Chaisa", "Compound", "Students"],
  ["Mtendere", "Compound", "East", "PHI", "Market"],
  ["Soweto Market", "Lusaka Central", "Town", "Vegetables", "Busy"],
  ["Kamwala", "Wholesale", "Affordable", "Salaula", "Indian"],
  ["City Market", "Town Centre", "Curios", "Handicrafts", "Tourists"],
  ["Kulima Tower", "Bus Station", "Intercity", "Market", "Iringa Mall"],

  // ============= SCIENCE & TECHNOLOGY =============
  ["Solar Panel", "Electricity", "Sun", "Power", "Renewable"],
  ["Borehole", "Water", "Drilling", "Underground", "Pump"],
  ["Starlink", "Satellite Internet", "Elon Musk", "Space", "Fast"],
  ["WhatsApp", "Messaging", "Green", "Meta", "Voice Notes"],
  ["TikTok", "Videos", "Chinese", "Dancing", "For You Page"],
  ["Facebook", "Social Media", "Mark Zuckerberg", "Blue", "Meta"],
  ["Twitter", "X", "Tweets", "Elon Musk", "Blue Bird"],
  ["ZESCO App", "Electricity", "Units", "Buy", "Mobile"],
  ["E-Voucher", "FISP", "Farming", "Fertilizer", "Electronic"],
  ["Smart License", "RTSA", "Driving", "Card", "Chip"],
  ["NRC", "National Registration", "Green Book", "ID", "Citizenship"],
  ["COVID-19", "Coronavirus", "Pandemic", "Vaccine", "Mask"],
  ["Airtel Money", "Mobile Money", "Red", "Withdraw", "Send"],
  ["MTN MoMo", "Mobile Money", "Yellow", "Transfer", "Withdraw"],

  // ============= HISTORY & HERITAGE =============
  ["Independence", "October 24", "1964", "Freedom", "Britain"],
  ["UNIP", "United National", "Independence Party", "One Party", "KK"],
  ["Federation", "Rhodesia Nyasaland", "Colonial", "1953-1963", "Three Countries"],
  ["Cha-cha-cha", "Rebellion", "1961", "Northern", "UNIP"],
  ["Harry Mwaanga Nkumbula", "ANC", "Freedom Fighter", "Politics", "Leader"],
  ["Simon Kapwepwe", "Vice President", "UNIP", "Bemba", "Leader"],
  ["Alice Lenshina", "Lumpa Church", "Religious", "Movement", "Chinsali"],
  ["Chiluba Era", "MMD", "Democracy", "1991", "Change"],
  ["Privatization", "Selling", "State Companies", "1990s", "MMD"],
  ["Northern Rhodesia", "Colonial Name", "Zambia", "British", "Territory"],
  ["Barotseland Agreement", "1964", "Western Province", "Litunga", "Treaty"],
  ["Freedom Statue", "Monument", "Independence", "Lusaka", "1974"],

  // ============= EDUCATION =============
  ["UNZA", "University of Zambia", "Great East Road", "Goma Lakes", "Students"],
  ["CBU", "Copperbelt University", "Kitwe", "Engineering", "Medicine"],
  ["Mulungushi University", "MU", "Kabwe", "Private", "Great North Road"],
  ["Apex Medical University", "Medicine", "Private", "Lusaka", "Health"],
  ["DMI St. Eugene", "Private University", "Chibombo", "Catholic", "Great North Road"],

  // ============= SHOPPING MALLS =============
  ["Manda Hill", "Mall", "Shopping Centre", "Cinema", "Great East"],
  ["Levy Junction", "Mall", "Shopping", "Church Road", "ZCAS"],
  ["East Park Mall", "Shopping", "Great East Road", "Chicagos", "Arcades"],
  ["Cosmopolitan Mall", "Cosmo", "Shopping", "Kafue Road", "Makeni"],
  ["Novare Pinnacle", "Mall", "Woodlands", "Shopping", "Roco Mamas"],

  // ============= MEDIA =============
  ["Times of Zambia", "Newspaper", "Daily", "Government", "Print"],
  ["Daily Mail", "Newspaper", "Government", "Daily", "Print"],
  ["News Diggers", "Online", "Independent", "Media", "News"],
  ["Mwebantu", "Online Media", "News", "Website", "Gossip"],
  ["ZNBC", "TV1", "National", "TV2", "Television"],
  ["Radio Phoenix", "89.5 FM", "Paddy", "Breakfast Show", "Sweetheart Radio"],
  ["QFM", "94.5", "Quality", "Radio", "News"],
  ["Hot FM", "87.7", "Youth", "Music", "Radio"],
  ["Power FM", "99.7", "Talk Radio", "Politics", "Current Affairs"],
  ["Muvi TV", "Private", "Channel", "Local Content", "Entertainment"],
  ["Prime TV", "Private Television", "News", "Local", "Channel"],

  // ============= EVERYDAY LIFE =============
  ["Brazier", "Mbaula", "Charcoal", "Cooking", "Heat"],
  ["Talk Time", "Airtime", "Units", "Phone", "Credit"],
  ["Cantor", "5 Liter", "Container", "Water", "Plastic"],
  ["Mosquito Net", "Bed", "Malaria", "Protection", "Sleep"],
  ["Chigayo", "Grinding", "Maize", "Machine", "Mealie Meal"],
  ["Minibus", "Blue Taxi", "Public Transport", "Conductor", "Komboni"],
  ["Rosa Bus", "Big Bus", "Public Transport", "Conductor", "Routes"],
  ["Kabende", "Groundnuts", "Maize", "Pound", "Katapa"],
  ["Pot", "Cooking", "Stove", "Round", "Fire"],
  ["Mpasa", "Sleeping", "Sit", "Traditional", "Mat"],
];
